### ISSUE TITLE
"Group ended before it began" Discussion

### ISSUE THREAD

**Issue by MauAbata** [denmuellner/ESP-ADF_Components_Test#1]
Came here from the PIO thread, since I had a similar error. It seems a couple pairs of `-Wl,--start-group`/`-Wl,--end-group` flags are being set out of order on the linker command. These flags come from the `esp-adf-libs` and `esp-sr` submodules in their CMakeLists.txt file.

As a *temporary* workaround, I've removed them in my local copy of esp-adf and it will compile against PlatformIO just fine without issues regarding circular dependencies. It looks like those flags were added in later in the file history, just before IDF v4 support was added to esp-adf.

I'm curious why the linker command is being generated with flags out of order from these component lists. The list of libraries included between the flags are also removed. Hopefully this points us in a somewhat useful direction.

Also, in these CMake files, the IDF_VER variable won't be correct, this is fixed on the latest dev branch of the platform: https://github.com/platformio/platform-espressif32/issues/558

**Comment by denmuellner** [comment]
Hi there,

just a few days ago someone came along with a painfully simple fix for this. There was indeed an additional `-Wl,--end-group` somewhere in the CMakeLists.txt files of the modules you mentioned. To fix this, a simple unflag command can be added in the platform.ini file. I just updated the repo also adding one of the ADF-examples.
